### ISSUE TITLE
License put in by default

### ISSUE THREAD

**Issue by codeOfRobin** [JohnSundell/SwiftPlate#19]
It looks like the generated files have the MIT License put in by default at the top of all files. Though it doesn't really make a difference to my org (we're open sourcing most of our stuff), people _might_ have a problem with it.
![screen shot 2016-11-23 at 4 42 27 pm](https://cloud.githubusercontent.com/assets/5009041/20559718/ded49b62-b19b-11e6-960c-47c9feab829a.png)

**Comment by JohnSundell** [comment]
Yeah, we should probably ask when SwiftPlate is run what license that the user wants to use, and add that both to the `LICENSE` file and as a header to all source files.

**Comment by kiliankoe** [comment]
Do source files really need a license header? Isn't a LICENSE file enough? Just feels so unnecessary 😕

**Comment by codeOfRobin** [comment]
I kinda agree with @kiliankoe . Can't we just us the XCode default of 

```
//
//  <File Name>
//  <org name>
//
//  Created by <Dev name> on 22/08/16.
//  Copyright © 2016 <Org Name>. All rights reserved.
//
```

**Comment by JohnSundell** [comment]
Yeah, the Xcode defaults should be enough actually 👍 (if people want to add a license header to the source + test file they can easily do so after SwiftPlate has generated them anyway)

**Comment by JohnSundell** [comment]
Resolved by https://github.com/vknabel/SwiftPlate/commit/9fce473ec3e944f38a66b3f3a39980dd76fd66bf
