### ISSUE TITLE
Support single target/scheme cross platform template to clean up Xcode

### ISSUE THREAD

**Issue by kdawgwilk** [JohnSundell/SwiftPlate#28]
I would like to see the template adopt the single scheme/target mentioned in this blog post: 

[Multiplatform Single Scheme Xcode Projects](http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/)

**Comment by JohnSundell** [comment]
@kdawgwilk sounds like a great idea! 👍 Maybe have it as an option as some developers prefer/require explicit schemes for each platform. Want to do the implementation?

**Comment by kdawgwilk** [comment]
I would love to add this support 😀 What is the best way to modify the template?  Does SwiftPlate support passing a git url to a repo for different templates?  Or would this there be 2 templates in this repo?

**Comment by JohnSundell** [comment]
@kdawgwilk Awesome! 👍 SwiftPlate supports giving a `--repo` (or `-r`) argument when run that points to an alternative repo that contains a template, but in this case we need to include both templates in the master repo. Maybe we can go the same approach as Xcode file/project templates and have folders that separate the differences in the templates?

**Comment by kdawgwilk** [comment]
How did you initially create the SwiftPlate templates?  Was it just a find and replace with {PROJECT}?

**Comment by JohnSundell** [comment]
@kdawgwilk Yeah exactly, I opened all the project files in Atom, and did a find and replace.

**Comment by kdawgwilk** [comment]
I have actually been looking into creating Xcode templates instead so I am not interested as much with this solution.  I will close this for now
