### ISSUE TITLE
Optional Gather coverage data

### ISSUE THREAD

**Issue by adellibovi** [JohnSundell/SwiftPlate#30]
Hi John,
First of all, thanks for this tool, it has been very helpful for me.
Do you think that an option to enable the "Gather coverage data" for all the testing targets would be useful? Does it suit in this project?
If so, I would like to work on that and prepare a PR.

**Comment by JohnSundell** [comment]
@adellibovi Sounds like a great idea! 👍 I'd actually be open to leaving it on per default, there's no real downside to gathering coverage data, right?

**Comment by adellibovi** [comment]
@JohnSundell totally agree! So, just to understand the directions for this feature: would this be an argument of the command only, both question and argument, or something implicit?

**Comment by JohnSundell** [comment]
@adellibovi I would say, just do it implicitly for now. If someone doesn't want code coverage to be generated they can just go into Xcode and un-tick the box 😄

**Comment by adellibovi** [comment]
@JohnSundell I guess you can close this now :)

**Comment by adellibovi** [comment]
I'm closing this since the PR got merged :)

**Comment by JohnSundell** [comment]
Great work @adellibovi! 🎉
