### ISSUE TITLE
Problem with Tests

### ISSUE THREAD

**Issue by gperdomor** [JohnSundell/SwiftPlate#34]
Hi, I try to run test using package manager and return this error: `error: no tests found to execute, create a module in your 'Tests' directory`

**Comment by JohnSundell** [comment]
@gperdomor Hi! Are you using the latest version of Swiftplate? Could you post a screenshot or description of how your folder structure looks like after Swiftplate has run?

**Comment by gperdomor** [comment]
I start again... Now works..

I will close this now
