### ISSUE TITLE
Github URL

### ISSUE THREAD

**Issue by onmyway133** [JohnSundell/SwiftPlate#38]
Hi, 👍 for this tool

I'm running through SwiftPlate, at this `Github URL` step

> Any GitHub URL that you'll be hosting this project at (for Podspec)? (Leave empty to use the remote URL of your repo: https://github.com/JohnSundell/SwiftPlate)

I think most people use Github now so it's more convenient if we support it directly. My proposal is to ask for `Github username` instead, and generate `Github URL` as `https://github.com/{user_name}/{project_name}`

What do you think? I would happily make a PR

**Comment by sahandnayebaziz** [comment]
Hey @onmyway133, can you clarify a little bit? Doesn't SwiftPlate already support what you're suggesting here?

Either A: give a url or B: use the remote URL of the repo ?

And couldn't automatically generating the URL by doing `{user_name}/{project_name}` not necessarily create the right URL for a repo if the project name is different, or, say, the project is actually hosted under an organization?

**Comment by JohnSundell** [comment]
@onmyway133 it seems like you're running SwiftPlate in its own repo, which is not the intended use 🙂 If SwiftPlate is being run in a Git repo (which is not SwiftPlate's own), it infers the correct URL. Closing this.
