### ISSUE TITLE
Doesn't work if ssh is not available

### ISSUE THREAD

**Issue by Brain89** [JohnSundell/SwiftPlate#4]
Can't generate project if ssh is not setup. 
Try to replace **git@github.com:JohnSundell/SwiftPlate.git** with **https://github.com/JohnSundell/SwiftPlate.git**

**Comment by JohnSundell** [comment]
Done! https://github.com/JohnSundell/SwiftPlate/commit/f11aeaf74d84d0668b4337dbb75fa0243d4751c3 ✅ 

Thanks for reporting 🚀
