### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by danielmartinprieto** [JohnSundell/SwiftPlate#54]
Hi! SwiftPlate is awesome, thanks for creating it. I was wondering if it makes sense to include a default .gitignore file for Xcode/Swift projects, I've seen other tools like this doing it.

**Comment by JohnSundell** [comment]
@danielmartinprieto Hi! Happy you like SwiftPlate 🎉 Sounds like a great idea - want to open a PR with that change?

**Comment by danielmartinprieto** [comment]
Sure! Let me do it when I'm in front of my computer.

**Comment by JohnSundell** [comment]
Implemented in #55 🎉
