### ISSUE TITLE
New SwiftPlate release

### ISSUE THREAD

**Issue by 3lvis** [JohnSundell/SwiftPlate#59]
Hi John,

I'm using the `brew` version of SwiftPlate and found a few issues that already have been fixed on master. [Looks like a lot of things have been fixed since the last release](https://github.com/JohnSundell/SwiftPlate/compare/1.3.0...master). Can you consider making a new `brew` version?

**Comment by JohnSundell** [comment]
Hey @3lvis! Thanks for the reminder, have totally missed to make a release for a while 😅 I just released version `1.4.0` based on the latest `master`. Honestly, I don't really know what is required for Homebrew to pick that up (if it's automatic or not), do you have any insight on that?

**Comment by kiliankoe** [comment]
It's not automatic, I just PR'd the new release: https://github.com/Homebrew/homebrew-core/pull/15772

**Comment by JohnSundell** [comment]
That's awesome, thanks a lot @kiliankoe! 🎉 Closing this now, as the Homebrew PR can be used to track further progress.

**Comment by 3lvis** [comment]
🎉
