### ISSUE TITLE
Test dependencies

### ISSUE THREAD

**Issue by MarvinNazari** [JohnSundell/SwiftPlate#6]
Wonder if we could add `Quick` and `Nimble` as test dependencies, would make the whole process faster! we can use `Carthage` for that.

**Comment by JohnSundell** [comment]
Great suggestion @MarvinNazari! We shouldn't assume that every project will use Quick, Nimble & Carthage, but we should add options for specifying what dependencies you want to use, and which package manager. 👍

**Comment by KieranHarper** [comment]
I've had a crack at this in PR #58
